export const trackImages: Record<string, string> = {
    "Spa-Francorchamps": "/tracks/spa.jpg",
    "Monza": "/tracks/monza.jpg",
    "Watkins Glen": "/tracks/watkins-glen.jpg",
    "Nürburgring": "/tracks/nurburgring.jpg",
    "Mount Panorama": "/tracks/mount-panorama.jpg",
    "Road Atlanta": "/tracks/road-atlanta.jpg",
    "Virginia International Raceway": "/tracks/vir.jpg",
    "Adelaide Street Circuit": "/tracks/adelaide.jpg",
    "Hockenheimring": "/tracks/hockenheim.jpg",
    "Circuit des 24 Heures du Mans": "/tracks/lemans.jpg",
    "Indianapolis Motor Speedway": "/tracks/indianapolis.jpg",
    "St. Petersburg Grand Prix": "/tracks/st-petersburg.jpg",
    "Red Bull Ring": "/tracks/red-bull-ring.jpg",
    "Suzuka International Racing Course": "/tracks/suzuka.jpg",
    "Autódromo José Carlos Pace": "/tracks/interlagos.jpg",
    "Fuji International Speedway": "/tracks/fuji.jpg",
    "Daytona International Speedway": "/tracks/daytona.jpg",
    "Mobility Resort Motegi": "/tracks/motegi.jpg",
    "Road America": "/tracks/road-america.jpg",
};